version: '3.8'

services:
  mysql:
    image: mysql:5.6
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: SkiStationDB
    ports:
      - "3306:3306"

  springboot:
    image: spring_ssp
    container_name: project-container
    ports:
      - "9090:9090"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/SkiStationDB?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=

volumes:
  mysql_data:
